import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1780604037460 implements MigrationInterface {
    name = 'Init1780604037460'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "FK_99797bb751811331b74d27865f3"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "FK_9bf4ed2454739ab4033ea5941dc"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "rejected_by"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "rejected_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_4d3bf49c959b227aabcc74e67fb"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_b3167c57663ae949d67436465b3"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "currency" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1bdffa25425538e630d8eb8a8bc"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_a88f466d39796d3081cf96e1b66"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "REL_92558c08091598f7a4439586cd"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "UQ_92558c08091598f7a4439586cda" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "currency_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "currency_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "suspendedById"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "suspendedById" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd"`);
        await queryRunner.query(`ALTER TABLE "provider" DROP CONSTRAINT "PK_6ab2f66d8987bf1bfdd6136a2d5"`);
        await queryRunner.query(`ALTER TABLE "provider" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "provider" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "provider" ADD CONSTRAINT "PK_6ab2f66d8987bf1bfdd6136a2d5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_464da95dc8a05470b2b158d4df6"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "wallet_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "provider_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "REL_464da95dc8a05470b2b158d4df"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "payment_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "payment_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "UQ_464da95dc8a05470b2b158d4df6" UNIQUE ("payment_id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "walletId" uuid`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "FK_99797bb751811331b74d27865f3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "FK_9bf4ed2454739ab4033ea5941dc" FOREIGN KEY ("rejected_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_b3167c57663ae949d67436465b3" FOREIGN KEY ("currency_id") REFERENCES "currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_4d3bf49c959b227aabcc74e67fb" FOREIGN KEY ("suspendedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1bdffa25425538e630d8eb8a8bc" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd" FOREIGN KEY ("provider_id") REFERENCES "provider"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_a88f466d39796d3081cf96e1b66" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_464da95dc8a05470b2b158d4df6" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_464da95dc8a05470b2b158d4df6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_a88f466d39796d3081cf96e1b66"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1bdffa25425538e630d8eb8a8bc"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_4d3bf49c959b227aabcc74e67fb"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_b3167c57663ae949d67436465b3"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "FK_9bf4ed2454739ab4033ea5941dc"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "FK_99797bb751811331b74d27865f3"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "walletId" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "UQ_464da95dc8a05470b2b158d4df6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "payment_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "payment_id" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "REL_464da95dc8a05470b2b158d4df" UNIQUE ("payment_id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "provider_id" integer`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "wallet_id" integer`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_464da95dc8a05470b2b158d4df6" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider" DROP CONSTRAINT "PK_6ab2f66d8987bf1bfdd6136a2d5"`);
        await queryRunner.query(`ALTER TABLE "provider" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "provider" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider" ADD CONSTRAINT "PK_6ab2f66d8987bf1bfdd6136a2d5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd" FOREIGN KEY ("provider_id") REFERENCES "provider"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "suspendedById"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "suspendedById" integer`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "currency_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "currency_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "UQ_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "REL_92558c08091598f7a4439586cd" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_a88f466d39796d3081cf96e1b66" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1bdffa25425538e630d8eb8a8bc" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "currency" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_b3167c57663ae949d67436465b3" FOREIGN KEY ("currency_id") REFERENCES "currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_4d3bf49c959b227aabcc74e67fb" FOREIGN KEY ("suspendedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "rejected_by"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "rejected_by" integer`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "FK_9bf4ed2454739ab4033ea5941dc" FOREIGN KEY ("rejected_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD CONSTRAINT "FK_99797bb751811331b74d27865f3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
